FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18 AS builder
WORKDIR /go/src/github.com/openshift/multi-operator-manager
COPY . .
RUN make

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9
COPY --from=builder /go/src/github.com/openshift/multi-operator-manager/multi-operator-manager /usr/bin/
ENTRYPOINT ["/usr/bin/multi-operator-manager"]
LABEL io.k8s.display-name="OpenShift Multi Operator Manager" \
	io.k8s.description="OpenShift Multi Operator Manager"
