---
apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-12T08:34:58Z"
    name: kube-root-ca.crt
    namespace: openshift-authentication
    resourceVersion: "15628"
    uid: 063af365-aeef-43d7-9239-1507809164b4
kind: ConfigMapList
metadata:
  resourceVersion: "248983"
