---
apiVersion: v1
items:
  - apiVersion: v1
    data:
      since: "2024-07-10"
    kind: ConfigMap
    metadata:
      creationTimestamp: "2024-07-10T22:51:23Z"
      name: kube-apiserver-legacy-service-account-token-tracking
      namespace: kube-system
      resourceVersion: "47"
      uid: 074b4fba-9dbe-40d9-a560-fdaf81a8e8e3
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      creationTimestamp: "2024-07-10T22:52:16Z"
      name: openshift-service-ca.crt
      namespace: kube-system
      resourceVersion: "7334"
      uid: d38d5838-77ef-4b9c-bef6-268c55082479
kind: ConfigMapList
metadata:
  resourceVersion: "25620"
