apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    synthetic.mom.openshift.io/controller-instance-name: example-ResourceSync
  name: cluster
status:
  conditions:
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    status: "False"
    type: ResourceSyncControllerDegraded
